### ISSUE TITLE
Support mapping branch names to different versions

### ISSUE THREAD

**Issue by gtback** [elastic/docs#1850]
Currently, there's an assumption that every branch that gets built is the same as the version number we want to show in the built documentation. We'd like to break that dependency.

Introduce a `branch_version_mapping` key in each book in conf.yaml, and add support to the Perl script to look at this key. For example:

```yaml
branch_version_mapping:
  branch-1: 1.1
  branch-2: 2.0
  legacy-0.7: 0.7
```

If this isn't included, then we'll default back to the current behavior of having the version and branch name match.
