### ISSUE TITLE
Add support for text labels on branches

### ISSUE THREAD

**Issue by uboness** [elastic/docs#29]
Such that if the branch name is `foobar-1.0`, we'll be able to assign it a `1.0` label for the generated site.

For example:

```yaml
watcher:
        url:        https://github.com/elastic/x-plugins.git
        current:    watcher-1.0
        branches:
            - watcher-1.0: 1.0
        private:    1
```
where `watcher-1.0` is the branch name, and `1.0` is the label for it in the site
